{
 "title": "trocksdb-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "db",
    "query": "label_values(engine_block_cache_size_bytes, db)"
   },
   {
    "name": "command",
    "label": "command",
    "query": "label_values(storage_command_total, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "available size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(store_size_bytes{type=\"available\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "capacity size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(store_size_bytes{type=\"capacity\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "store size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(engine_size_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Rocksdb - $db", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "db" },
  {
   "title": "cf size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(engine_size_bytes) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "store size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(engine_size_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Get Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_memtable_efficiency{db=\"$db\", type=\"memtable_hit\"}[1m]))",
     "legendFormat": "memtable"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=~\"block_cache_data_hit|block_cache_filter_hit\"}[1m]))",
     "legendFormat": "block_cache"
    },
    {
     "expr": "sum(rate(engine_get_served{db=\"$db\", type=\"get_hit_l0\"}[1m]))",
     "legendFormat": "l0"
    },
    {
     "expr": "sum(rate(engine_get_served{db=\"$db\", type=\"get_hit_l1\"}[1m]))",
     "legendFormat": "l1"
    },
    {
     "expr": "sum(rate(engine_get_served{db=\"$db\", type=\"get_hit_l2_and_up\"}[1m]))",
     "legendFormat": "l2_and_up"
    }
   ]
  },
  {
   "title": "Get Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(engine_get_micro_seconds{db=\"$db\",type=\"get_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_get_micro_seconds{db=\"$db\",type=\"get_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_get_micro_seconds{db=\"$db\",type=\"get_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_get_micro_seconds{db=\"$db\",type=\"get_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Seek Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_locate{db=\"$db\", type=\"number_db_seek\"}[1m]))",
     "legendFormat": "seek"
    },
    {
     "expr": "sum(rate(engine_locate{db=\"$db\", type=\"number_db_seek_found\"}[1m]))",
     "legendFormat": "seek_found"
    },
    {
     "expr": "sum(rate(engine_locate{db=\"$db\", type=\"number_db_next\"}[1m]))",
     "legendFormat": "next"
    },
    {
     "expr": "sum(rate(engine_locate{db=\"$db\", type=\"number_db_next_found\"}[1m]))",
     "legendFormat": "next_found"
    },
    {
     "expr": "sum(rate(engine_locate{db=\"$db\", type=\"number_db_prev\"}[1m]))",
     "legendFormat": "prev"
    },
    {
     "expr": "sum(rate(engine_locate{db=\"$db\", type=\"number_db_prev_found\"}[1m]))",
     "legendFormat": "prev_found"
    }
   ]
  },
  {
   "title": "Seek Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(engine_seek_micro_seconds{db=\"$db\",type=\"seek_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_seek_micro_seconds{db=\"$db\",type=\"seek_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_seek_micro_seconds{db=\"$db\",type=\"seek_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_seek_micro_seconds{db=\"$db\",type=\"seek_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Write Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_write_served{db=\"$db\", type=~\"write_done_by_self|write_done_by_other\"}[1m]))",
     "legendFormat": "done"
    },
    {
     "expr": "sum(rate(engine_write_served{db=\"$db\", type=\"write_timeout\"}[1m]))",
     "legendFormat": "timeout"
    },
    {
     "expr": "sum(rate(engine_write_served{db=\"$db\", type=\"write_with_wal\"}[1m]))",
     "legendFormat": "with_wal"
    }
   ]
  },
  {
   "title": "Write Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(engine_write_micro_seconds{db=\"$db\",type=\"write_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_write_micro_seconds{db=\"$db\",type=\"write_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_write_micro_seconds{db=\"$db\",type=\"write_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_write_micro_seconds{db=\"$db\",type=\"write_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "WAL Sync Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_wal_file_synced{db=\"$db\"}[1m]))",
     "legendFormat": "sync"
    }
   ]
  },
  {
   "title": "WAL Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(engine_wal_file_sync_micro_seconds{db=\"$db\",type=\"wal_file_sync_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_wal_file_sync_micro_seconds{db=\"$db\",type=\"wal_file_sync_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_wal_file_sync_micro_seconds{db=\"$db\",type=\"wal_file_sync_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_wal_file_sync_micro_seconds{db=\"$db\",type=\"wal_file_sync_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Compaction Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_event_total{db=\"$db\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Compaction Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(engine_compaction_time{db=\"$db\",type=\"compaction_time_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_compaction_time{db=\"$db\",type=\"compaction_time_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_compaction_time{db=\"$db\",type=\"compaction_time_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_compaction_time{db=\"$db\",type=\"compaction_time_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "SST Read Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(engine_sst_read_micros{db=\"$db\", type=\"sst_read_micros_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_sst_read_micros{db=\"$db\", type=\"sst_read_micros_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_sst_read_micros{db=\"$db\", type=\"sst_read_micros_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_sst_read_micros{db=\"$db\", type=\"sst_read_micros_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Write Stall Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(engine_write_stall{db=\"$db\", type=\"write_stall_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_write_stall{db=\"$db\", type=\"write_stall_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_write_stall{db=\"$db\", type=\"write_stall_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_write_stall{db=\"$db\", type=\"write_stall_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Memtable Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(engine_memory_bytes{db=\"$db\", type=\"mem-tables\"}) by (cf)",
     "legendFormat": "{{cf}}"
    }
   ]
  },
  {
   "title": "Memtable Hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_memtable_efficiency{db=\"$db\", type=\"memtable_hit\"}[1m])) / (sum(rate(engine_memtable_efficiency{db=\"$db\", type=\"memtable_hit\"}[1m])) + sum(rate(engine_memtable_efficiency{db=\"$db\", type=\"memtable_miss\"}[1m])))",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(engine_block_cache_size_bytes{db=\"$db\"}) by(cf)",
     "legendFormat": "{{cf}}"
    }
   ]
  },
  {
   "title": "Block Cache Hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_hit\"}[1m])) / (sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_hit\"}[1m])) + sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_miss\"}[1m])))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_data_hit\"}[1m])) / (sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_data_hit\"}[1m])) + sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_data_miss\"}[1m])))",
     "legendFormat": "data"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_filter_hit\"}[1m])) / (sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_filter_hit\"}[1m])) + sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_filter_miss\"}[1m])))",
     "legendFormat": "filter"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_index_hit\"}[1m])) / (sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_index_hit\"}[1m])) + sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_index_miss\"}[1m])))",
     "legendFormat": "index"
    },
    {
     "expr": "sum(rate(engine_bloom_efficiency{db=\"$db\", type=\"bloom_filter_prefix_useful\"}[1m])) / sum(rate(engine_bloom_efficiency{db=\"$db\", type=\"bloom_filter_prefix_checked\"}[1m]))",
     "legendFormat": "bloom filter prefix"
    }
   ]
  },
  {
   "title": "Block Cache Flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"block_cache_bytes_read\"}[1m]))",
     "legendFormat": "total_read"
    },
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"block_cache_bytes_write\"}[1m]))",
     "legendFormat": "total_written"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_data_bytes_insert\"}[1m]))",
     "legendFormat": "data_insert"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_filter_bytes_insert\"}[1m]))",
     "legendFormat": "filter_insert"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_filter_bytes_evict\"}[1m]))",
     "legendFormat": "filter_evict"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_index_bytes_insert\"}[1m]))",
     "legendFormat": "index_insert"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_index_bytes_evict\"}[1m]))",
     "legendFormat": "index_evict"
    }
   ]
  },
  {
   "title": "Block Cache Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_add\"}[1m]))",
     "legendFormat": "total_add"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_data_add\"}[1m]))",
     "legendFormat": "data_add"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_filter_add\"}[1m]))",
     "legendFormat": "filter_add"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_index_add\"}[1m]))",
     "legendFormat": "index_add"
    },
    {
     "expr": "sum(rate(engine_cache_efficiency{db=\"$db\", type=\"block_cache_add_failures\"}[1m]))",
     "legendFormat": "add_failures"
    }
   ]
  },
  {
   "title": "Keys Flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"number_keys_read\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"number_keys_written\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"number_keys_updated\"}[1m]))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(rate(engine_compaction_num_corrupt_keys{db=\"$db\"}[1m]))",
     "legendFormat": "corrupt"
    }
   ]
  },
  {
   "title": "Total Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_estimate_num_keys{db=\"$db\"}) by (cf)",
     "legendFormat": "{{cf}}"
    }
   ]
  },
  {
   "title": "Read Flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"compact_bytes_read\"}[1m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"iter_bytes_read\"}[1m]))",
     "legendFormat": "scan"
    }
   ]
  },
  {
   "title": "Bytes / Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(engine_bytes_per_read{db=\"$db\",type=\"bytes_per_read_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_bytes_per_read{db=\"$db\",type=\"bytes_per_read_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_bytes_per_read{db=\"$db\",type=\"bytes_per_read_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_bytes_per_read{db=\"$db\",type=\"bytes_per_read_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Write Flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"wal_file_bytes\"}[1m]))",
     "legendFormat": "wal"
    },
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"compact_bytes_written\"}[1m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Bytes / Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(engine_bytes_per_write{db=\"$db\",type=\"bytes_per_write_max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(engine_bytes_per_write{db=\"$db\",type=\"bytes_per_write_percentile99\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(engine_bytes_per_write{db=\"$db\",type=\"bytes_per_write_percentile95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(engine_bytes_per_write{db=\"$db\",type=\"bytes_per_write_average\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Compaction Flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_compaction_flow_bytes{db=\"$db\", type=\"bytes_read\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(engine_compaction_flow_bytes{db=\"$db\", type=\"compact_bytes_written\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(engine_flow_bytes{db=\"$db\", type=\"flush_write_bytes\"}[1m]))",
     "legendFormat": "flushed"
    }
   ]
  },
  {
   "title": "Compaction Pending  Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_pending_compaction_bytes{db=\"$db\"}[1m])) by (cf)",
     "legendFormat": "{{cf}}"
    }
   ]
  },
  {
   "title": "Read Amplication",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_read_amp_flow_bytes{db=\"$db\", type=\"read_amp_total_read_bytes\"}[1m])) by (job) / sum(rate(engine_read_amp_flow_bytes{db=\"$db\", type=\"read_amp_estimate_useful_bytes\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(engine_compression_ratio{db=\"$db\"}) by (level)",
     "legendFormat": "level - {{level}}"
    }
   ]
  },
  {
   "title": "Number of Snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_num_snapshots{db=\"$db\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Oldest Snapshots Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "engine_oldest_snapshot_duration{db=\"$db\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}